### ISSUE TITLE
Add a python file

### ISSUE THREAD

**Issue by Yash-Kalekar** [Yash-Kalekar/Plant-Disease-Detection-using-Deep-Learning-and-Neural-Networks-using-Python#1]
I want people from the open source community to collab with me in this project.

Please add a python file to run the model

**Comment by Manish-373** [comment]
Hi Yash i am ready to contribute to your project. I can buid a python file to run the model.

**Comment by patilvaishnavi40** [comment]
Hi Yash i am ready to contribute to your project . I can add error handling, progress indicator, model and label caching , top prediction , general improvements,  additional preprocessing settings, customization of image size.
